/* ============================================================
   Build-time fetch for the home page price chart.

       set OPENSEA_API_KEY=...        (PowerShell: $env:OPENSEA_API_KEY = '...')
       node tools/fetch-floor.js

   Writes data/floor.json.

   WHY THIS IS A BUILD STEP AND NOT A FETCH IN THE PAGE
   The OpenSea API sends no CORS headers, so a browser can never
   call it — key or no key. Running it here keeps the key off the
   client entirely, which is the right place for it anyway.

   WHAT THE NUMBERS ACTUALLY ARE
   OpenSea publishes the *current* floor but no floor history, so
   the series is the lowest completed sale per day — a floor proxy,
   not the listing floor. The chart says so on its face. The single
   current floor figure is the real one, straight from /stats.
   ============================================================ */

const fs = require('fs');
const path = require('path');

const SLUG = 'secretsocietyofwhales';
const DAYS = 90;
const KEY = process.env.OPENSEA_API_KEY;

if (!KEY) {
    console.error('Set OPENSEA_API_KEY first. This script never hardcodes it.');
    process.exit(1);
}

const headers = { 'x-api-key': KEY, accept: 'application/json' };

function get(url) {
    return fetch(url, { headers }).then(function (res) {
        if (!res.ok) throw new Error(url + ' -> ' + res.status);
        return res.json();
    });
}

function dayOf(unixSeconds) {
    return new Date(unixSeconds * 1000).toISOString().slice(0, 10);
}

async function main() {
    const stats = await get('https://api.opensea.io/api/v2/collections/' + SLUG + '/stats');
    const after = Math.floor(Date.now() / 1000) - DAYS * 86400;

    const lowest = {};        /* day -> lowest sale in ETH */
    const counts = {};        /* day -> number of sales   */
    let cursor = null;
    let pages = 0;

    do {
        const url = 'https://api.opensea.io/api/v2/events/collection/' + SLUG +
                    '?event_type=sale&limit=50&after=' + after +
                    (cursor ? '&next=' + encodeURIComponent(cursor) : '');
        const page = await get(url);

        (page.asset_events || []).forEach(function (e) {
            if (!e.payment || e.payment.symbol !== 'ETH') return;   /* ignore WETH/USDC mixes */
            const decimals = e.payment.decimals || 18;
            const items = e.quantity && e.quantity > 0 ? e.quantity : 1;
            const price = Number(e.payment.quantity) / Math.pow(10, decimals) / items;
            if (!isFinite(price) || price <= 0) return;

            const day = dayOf(e.event_timestamp);
            lowest[day] = lowest[day] === undefined ? price : Math.min(lowest[day], price);
            counts[day] = (counts[day] || 0) + 1;
        });

        cursor = page.next || null;
        pages++;
        process.stdout.write('\rpages: ' + pages + '  days so far: ' + Object.keys(lowest).length);
    } while (cursor && pages < 60);

    const series = Object.keys(lowest).sort().map(function (day) {
        return { date: day, eth: Number(lowest[day].toFixed(6)), sales: counts[day] };
    });

    /* Nothing sane came back — bail before overwriting good data.
       Matters most when this runs unattended in CI: a bad response
       would otherwise commit an empty chart over a working one. */
    if (series.length === 0) {
        throw new Error('no sales found in the last ' + DAYS + ' days — refusing to overwrite data/floor.json');
    }

    const out = {
        collection: 'Secret Society of Whales',
        slug: SLUG,
        capturedAt: new Date().toISOString(),
        currentFloorEth: stats.total ? stats.total.floor_price : null,
        totalVolumeEth: stats.total ? Number(stats.total.volume.toFixed(2)) : null,
        owners: stats.total ? stats.total.num_owners : null,
        note: 'series = lowest completed sale per day (floor proxy); currentFloorEth is the live listing floor',
        series: series
    };

    const dir = path.join(__dirname, '..', 'data');
    fs.mkdirSync(dir, { recursive: true });

    const json = JSON.stringify(out, null, 2);
    fs.writeFileSync(path.join(dir, 'floor.json'), json);

    /* Also emit it as a plain script. A page opened from disk cannot
       fetch() a local JSON file — Chrome blocks it — but a <script> tag
       loads fine, so this is what the chart actually reads. The .json
       stays for anything that wants the raw data. */
    fs.writeFileSync(
        path.join(dir, 'floor.js'),
        '/* Auto-generated by tools/fetch-floor.js — do not edit. */\n' +
        'window.FLOOR_DATA = ' + json + ';\n'
    );

    console.log('\n' + series.length + ' days written to data/floor.json + data/floor.js');
    console.log('current floor: ' + out.currentFloorEth + ' ETH');
}

main().catch(function (err) {
    console.error('\n' + err.message);
    process.exit(1);
});
