/* ============================================================
   Find the gold-skin whales for the easter egg.

       node tools/find-gold.js

   Writes data/gold.js (window.GOLD_WHALES = [...]).

   Gold is rare — a 40-token sample missed it entirely — so the
   page must not hunt for one at runtime. This scans once, offline,
   and ships a short list.

   Whales on WOODY/ARMY backgrounds are skipped: the easter egg
   knocks the background out by keying the corner colour, which
   only works on the flat single-colour backgrounds. Textured ones
   would key ragged.
   ============================================================ */

const fs = require('fs');
const path = require('path');

const CID = 'QmdAxHGSCS2NftXn52WbumMn2ENMKXcmk55QgXbmWr86KL';
const GATEWAY = 'https://gateway.pinata.cloud/ipfs/';
const SUPPLY = 10000;

const WANT = 60;          /* enough variety for an easter egg   */
const SCAN_LIMIT = 3500;  /* give up after this many tokens     */
const CONCURRENCY = 24;
const TEXTURED = ['wood', 'army'];

const found = [];
let scanned = 0;
let cursor = 0;

/* walk the id space in a fixed stride so the sample is spread
   across the collection rather than clustered at the start */
const STRIDE = 7;
function nextId() {
    if (cursor >= SCAN_LIMIT) return null;
    const id = ((cursor * STRIDE) % SUPPLY) + 1;
    cursor++;
    return id;
}

function trait(attrs, type) {
    const hit = (attrs || []).find(function (a) { return a.trait_type === type; });
    return hit ? String(hit.value) : '';
}

async function fetchOne(id) {
    const ctrl = new AbortController();
    const timer = setTimeout(function () { ctrl.abort(); }, 20000);
    try {
        const res = await fetch(GATEWAY + CID + '/' + id, { signal: ctrl.signal });
        if (!res.ok) return null;
        return await res.json();
    } catch (err) {
        return null;
    } finally {
        clearTimeout(timer);
    }
}

async function worker() {
    while (found.length < WANT) {
        const id = nextId();
        if (id === null) return;

        const meta = await fetchOne(id);
        scanned++;

        if (scanned % 50 === 0) {
            process.stdout.write('\rscanned ' + scanned + '  gold found ' + found.length);
        }
        if (!meta) continue;

        const skin = trait(meta.attributes, 'Skin');
        const bg = trait(meta.attributes, 'Background');
        if (!/gold/i.test(skin)) continue;
        if (TEXTURED.indexOf(bg.toLowerCase()) !== -1) continue;

        found.push({
            id: id,
            image: meta.image,
            bg: bg,
            hat: trait(meta.attributes, 'Hat'),
            outfit: trait(meta.attributes, 'Outfit')
        });
    }
}

async function main() {
    const pool = [];
    for (let i = 0; i < CONCURRENCY; i++) pool.push(worker());
    await Promise.all(pool);

    found.sort(function (a, b) { return a.id - b.id; });

    const dir = path.join(__dirname, '..', 'data');
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(
        path.join(dir, 'gold.js'),
        '/* Auto-generated by tools/find-gold.js — do not edit.\n' +
        '   ' + found.length + ' gold-skin whales found in ' + scanned + ' scanned.\n' +
        '   Textured (Wood/Army) backgrounds excluded — they do not chroma-key cleanly. */\n' +
        'window.GOLD_WHALES = ' + JSON.stringify(found, null, 2) + ';\n'
    );

    console.log('\n' + found.length + ' gold whales from ' + scanned + ' scanned -> data/gold.js');
    if (found.length) {
        console.log('sample: ' + found.slice(0, 8).map(function (w) { return '#' + w.id; }).join(', '));
    }
}

main().catch(function (e) { console.error(e.message); process.exit(1); });
